version: '3.8'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: is_server
    image: is_server_image
    ports:
      - 8000:8000
    restart: always