name: Deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish-server-docker:
    name: publish-server-docker
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./server
          file: ./server/Dockerfile
          push: true
          tags: richstardocker/is_server:latest
 
  deploy:
        name: Deploy
        runs-on: ubuntu-latest
        needs: 
            - publish-server-docker

        steps:
            - uses: actions/checkout@v4
        
            - name: webfactory/ssh-agent
              uses: webfactory/ssh-agent@v0.9.0
              with:
                ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

            - name: Deploy to server
              run: |
                ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.DROPLET_IP }} "bash -s" < ./scripts/deploy.sh